---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SimpleWordsChannel:
    Type: String
    Description: |
      Slack channel the app will watch.
  SlackToken:
    Type: String
    Description: |
      Slack token for the app this code will act as.

Resources:
  SimpleWordsRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          "/":
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                # Hardcode SimpleWordsApplication.Arn to resolve circular dependency
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:SimpleWordsApplication${AWS::StackName}/invocations"
              responses: {}

  SimpleWordsApplication:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "SimpleWordsApplication${AWS::StackName}"
      Handler: main.lambda_main
      Runtime: python3.7
      CodeUri: main.py
      Timeout: 10
      Environment:
        Variables:
          SIMPLE_WORDS_CHANNEL: !Ref SimpleWordsChannel
          SLACK_TOKEN: !Ref SlackToken
      Events:
        SimpleWordsWebhook:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: SimpleWordsRestApi

Outputs:
  WebhookUrl:
    Description: URL of the application webhook
    Value: !Sub "https://${SimpleWordsRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
